"""
============================================================
GER
S29
E6.2
Statistical Observatory
Input / Output
============================================================

Loads and validates observational data generated by
the GER CORE.

This module performs no statistical analysis.

Author
------
GER Project
"""

from __future__ import annotations

from pathlib import Path
from typing import Union

import pandas as pd

from .config import (
    SUPPORTED_INPUT_FORMATS,
)

# ============================================================
# Version
# ============================================================

IO_VERSION = "1.0"

# ============================================================
# Public API
# ============================================================

__all__ = [
    "load_dataframe",
    "validate_dataframe",
    "load",
]

# ============================================================
# Data Loading
# ============================================================

def load_dataframe(
    filename: Union[str, Path]
) -> pd.DataFrame:
    """
    Load observational data from disk.
    """

    filename = Path(filename)

    suffix = filename.suffix.lower()

    if suffix not in SUPPORTED_INPUT_FORMATS:
        raise ValueError(
            f"Unsupported file format: {suffix}"
        )

    if suffix == ".csv":
        return pd.read_csv(filename)

    if suffix == ".json":
        return pd.read_json(filename)

    if suffix == ".parquet":
        return pd.read_parquet(filename)

    raise RuntimeError(
        "Unknown input format."
    )

# ============================================================
# Validation
# ============================================================

def validate_dataframe(
    dataframe: pd.DataFrame
) -> None:
    """
    Validate observational dataset.
    """

    if dataframe.empty:
        raise ValueError(
            "Empty dataframe."
        )

    if dataframe.shape[0] == 0:
        raise ValueError(
            "Dataset contains no samples."
        )

    if dataframe.shape[1] == 0:
        raise ValueError(
            "Dataset contains no observables."
        )

# ============================================================
# High Level Loader
# ============================================================

def load(
    filename: Union[str, Path]
) -> pd.DataFrame:
    """
    Load and validate a dataset.
    """

    dataframe = load_dataframe(filename)

    validate_dataframe(dataframe)

    return dataframe

# ============================================================
# Summary
# ============================================================

def _summary(
    dataframe: pd.DataFrame
) -> None:

    print("=" * 60)
    print("GER Statistical Observatory")
    print("Input Summary")
    print("=" * 60)

    print()

    print(f"Samples     : {len(dataframe)}")
    print(f"Observables : {len(dataframe.columns)}")

    print()

    print("Columns:")

    for column in dataframe.columns:
        print(f"  - {column}")

    print()

# ============================================================
# Self Test
# ============================================================

def main():

    print("=" * 60)
    print("GER S29 E6.2")
    print("IO Module")
    print("=" * 60)

    print()
    print("This module is intended to be imported.")
    print("Example:")
    print()

    print(
        "data = load('observables.csv')"
    )

    print()

if __name__ == "__main__":
    main()
