"""
============================================================
GER
S29
E6.2
Statistical Observatory
Statistics
============================================================

Computes descriptive statistics for the Signature Space
generated by S29_E6.3.

This module operates only on the signature dataset.

Author
------
GER Project
"""

from __future__ import annotations

import pandas as pd

from .io import load_signatures

# ============================================================
# Version
# ============================================================

STATISTICS_VERSION = "1.0"

# ============================================================
# Public API
# ============================================================

__all__ = [
    "summary_statistics",
    "covariance_matrix",
    "correlation_matrix",
    "compute_statistics",
]

# ============================================================
# Descriptive Statistics
# ============================================================

def summary_statistics(
    signatures: pd.DataFrame,
) -> pd.DataFrame:
    """
    Compute descriptive statistics.
    """

    return signatures.describe().T


# ============================================================
# Covariance
# ============================================================

def covariance_matrix(
    signatures: pd.DataFrame,
) -> pd.DataFrame:
    """
    Compute covariance matrix.
    """

    return signatures.cov()


# ============================================================
# Correlation
# ============================================================

def correlation_matrix(
    signatures: pd.DataFrame,
) -> pd.DataFrame:
    """
    Compute Pearson correlation matrix.
    """

    return signatures.corr(method="pearson")


# ============================================================
# High-Level API
# ============================================================

def compute_statistics(
    signatures: pd.DataFrame,
) -> dict:
    """
    Compute all statistical products.
    """

    return {

        "summary": summary_statistics(signatures),

        "covariance": covariance_matrix(signatures),

        "correlation": correlation_matrix(signatures),
    }


# ============================================================
# Summary
# ============================================================

def _print_summary(results: dict):

    print("=" * 60)
    print("GER Statistical Observatory")
    print("Statistics")
    print("=" * 60)
    print()

    print("Variables:")

    for variable in results["summary"].index:
        print(f"  - {variable}")

    print()

    print("Samples :")

    print(
        int(
            results["summary"]
            .loc[:, "count"]
            .iloc[0]
        )
    )

    print()


# ============================================================
# Self Test
# ============================================================

def main():

    print("=" * 60)
    print("GER S29 E6.2")
    print("Statistics Module")
    print("=" * 60)
    print()

    signatures = load_signatures()

    results = compute_statistics(
        signatures
    )

    _print_summary(results)

    print("Summary Statistics")
    print("------------------")
    print(results["summary"])
    print()

    print("Correlation Matrix")
    print("------------------")
    print(results["correlation"])
    print()

    print("Covariance Matrix")
    print("-----------------")
    print(results["covariance"])
    print()


if __name__ == "__main__":
    main()
