"""
============================================================
GER
S29
E6.2
Statistical Observatory
Models
============================================================

Data models used by the Statistical Observatory.

These classes contain no scientific logic.
They provide typed containers for the results
generated by the Statistical Observatory.

Author
------
GER Project
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List

# ============================================================
# Version
# ============================================================

MODELS_VERSION = "1.0"

# ============================================================
# Base Summary
# ============================================================

@dataclass(slots=True)
class Summary:

    values: Dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================
# Individual Summaries
# ============================================================

@dataclass(slots=True)
class StatisticsSummary(Summary):
    pass


@dataclass(slots=True)
class OccupancySummary(Summary):
    pass


@dataclass(slots=True)
class DensitySummary(Summary):
    pass


@dataclass(slots=True)
class ConcentrationSummary(Summary):
    pass


@dataclass(slots=True)
class StabilitySummary(Summary):
    pass


@dataclass(slots=True)
class OutlierSummary(Summary):
    pass


# ============================================================
# Statistical Certificate
# ============================================================

@dataclass(slots=True)
class StatisticalCertificate:

    module: str

    version: str

    timestamp: str

    samples: int

    dimensions: List[str]

    statistics: StatisticsSummary

    occupancy: OccupancySummary

    density: DensitySummary

    concentration: ConcentrationSummary

    stability: StabilitySummary

    outliers: OutlierSummary

    def to_dict(self):

        return {

            "module": self.module,

            "version": self.version,

            "timestamp": self.timestamp,

            "samples": self.samples,

            "dimensions": self.dimensions,

            "statistics":
                self.statistics.values,

            "occupancy":
                self.occupancy.values,

            "density":
                self.density.values,

            "concentration":
                self.concentration.values,

            "stability":
                self.stability.values,

            "outliers":
                self.outliers.values,
        }


# ============================================================
# Public API
# ============================================================

__all__ = [

    "StatisticsSummary",

    "OccupancySummary",

    "DensitySummary",

    "ConcentrationSummary",

    "StabilitySummary",

    "OutlierSummary",

    "StatisticalCertificate",
]
