"""
=============================================================
S29_E9/config.py
=============================================================

Configuration

Trajectory Relaxation Analysis

Every configurable parameter used by E9 is centralized here.

=============================================================
"""

from __future__ import annotations


# ============================================================
# Experiment Information
# ============================================================

EXPERIMENT_NAME = "S29_E9"

EXPERIMENT_TITLE = (
    "Trajectory Relaxation Analysis"
)

VERSION = "1.1"


# ============================================================
# Input
# ============================================================

INPUT_FILENAME = "trajectory.csv"

SIGMA_COLUMN = "sigma"


# ============================================================
# Observables
# ============================================================

OBSERVABLES = [

    "delta_sigma",

    "path_length",

    "velocity",

    "acceleration",

    "second_difference",

    "second_difference_rate",

]


# ============================================================
# Candidate Models
# ============================================================

MODELS = [

    "linear",

    "quadratic",

    "exponential",

    "power",

    "logarithmic",

    "inverse",

    "exp_saturation",

    "michaelis_menten",

    "logistic",

]


# ============================================================
# Statistical Metrics
# ============================================================

METRICS = [

    "r2",

    "rmse",

    "mae",

    "aic",

    "bic",

]


# ============================================================
# Numerical Parameters
# ============================================================

EPSILON = 1e-12

MAX_ITERATIONS = 10000

MIN_REQUIRED_POINTS = 20


# ============================================================
# Model Selection Policy
# ============================================================

#
# Available policies
#
#   "balanced"
#   "aic"
#   "bic"
#   "r2"
#

MODEL_SELECTION_POLICY = "balanced"

PRIMARY_SELECTION_METRIC = "aic"

SECONDARY_SELECTION_METRIC = "bic"

TERTIARY_SELECTION_METRIC = "r2"

USE_BIC_AS_TIEBREAKER = True

MIN_R2_ACCEPTABLE = 0.95


# ============================================================
# Residual Analysis
# ============================================================

ENABLE_RESIDUAL_ANALYSIS = True

ENABLE_RESIDUAL_NORMALITY = True

ENABLE_RESIDUAL_AUTOCORRELATION = True


# ============================================================
# Confidence Classification
# ============================================================

HIGH_CONFIDENCE_R2 = 0.995

MEDIUM_CONFIDENCE_R2 = 0.980

LOW_CONFIDENCE_R2 = 0.950


# ============================================================
# Output Files
# ============================================================

FIT_SUMMARY_CSV = "E9_fit_summary.csv"

BEST_MODELS_CSV = "E9_best_models.csv"

MODEL_PARAMETERS_CSV = "E9_model_parameters.csv"

STATISTICS_JSON = "E9_statistics.json"

REPORT_TXT = "E9_report.txt"


# ============================================================
# Dashboard
# ============================================================

GENERATE_DASHBOARD = True

EXPORT_ALL_MODEL_RESULTS = True


# ============================================================
# Report
# ============================================================

REPORT_PRECISION = 6

REPORT_WIDTH = 80

INCLUDE_MODEL_RANKING = True

INCLUDE_PARAMETERS = True

INCLUDE_RESIDUAL_ANALYSIS = True

INCLUDE_CERTIFICATE = True


# ============================================================
# Certificate
# ============================================================

GENERATE_FIT_CERTIFICATE = True


# ============================================================
# Public API
# ============================================================

def available_observables() -> list[str]:
    """
    Return observable names.
    """
    return list(OBSERVABLES)


def available_models() -> list[str]:
    """
    Return candidate models.
    """
    return list(MODELS)


def available_metrics() -> list[str]:
    """
    Return statistical metrics.
    """
    return list(METRICS)


def get_output_files() -> list[str]:
    """
    Return every output file generated by E9.
    """

    return [

        FIT_SUMMARY_CSV,

        BEST_MODELS_CSV,

        MODEL_PARAMETERS_CSV,

        STATISTICS_JSON,

        REPORT_TXT,

    ]
