"""
=============================================================
S29_E9/dashboard.py
=============================================================

Trajectory Relaxation Analysis

Dashboard Builder

Creates a structured dashboard from the numerical
results produced by the experiment.

=============================================================
"""

from __future__ import annotations

from datetime import datetime

from .config import (
    EXPERIMENT_NAME,
    EXPERIMENT_TITLE,
    VERSION,
)

from .selection import (
    selection_summary,
)

from .statistics import (
    analyze_fit,
)

from .fitting import (
    FitResult,
)


# ============================================================
# Metadata
# ============================================================

def build_metadata():
    """
    Dashboard metadata.
    """

    return {

        "experiment":

            EXPERIMENT_NAME,

        "title":

            EXPERIMENT_TITLE,

        "version":

            VERSION,

        "generated":

            datetime.now().isoformat(),

    }


# ============================================================
# Best Model
# ============================================================

def best_model_panel(
    result: FitResult,
):
    """
    Best model information.
    """

    if result is None:

        return {

            "available": False,

        }

    return {

        "available": True,

        "model":

            result.model,

        "parameters":

            list(result.parameters),

        "r2":

            result.r2,

        "rmse":

            result.rmse,

        "mae":

            result.mae,

        "rss":

            result.rss,

        "aic":

            result.aic,

        "bic":

            result.bic,

    }


# ============================================================
# Residual Panel
# ============================================================

def residual_panel(
    result: FitResult,
):
    """
    Residual statistics.
    """

    if result is None:

        return {

            "available": False,

        }

    return {

        "available": True,

        "statistics":

            analyze_fit(

                result

            ),

    }


# ============================================================
# Selection Panel
# ============================================================

def selection_panel(
    results,
):
    """
    Selection information.
    """

    return selection_summary(

        results

    )


# ============================================================
# Experiment Panel
# ============================================================

def experiment_panel(
    results,
):
    """
    General experiment statistics.
    """

    successful = [

        r

        for r in results

        if r.success

    ]

    return {

        "models_tested":

            len(results),

        "successful_fits":

            len(successful),

        "failed_fits":

            len(results)

            - len(successful),

    }

  # ============================================================
# Ranking Panel
# ============================================================

def ranking_panel(
    results,
):
    """
    Ranking of all fitted models.
    """

    ranking = []

    ordered = sorted(

        results,

        key=lambda r: (

            np.inf if r.aic is None else r.aic

        )

    )

    for result in ordered:

        ranking.append(

            {

                "model":

                    result.model,

                "success":

                    result.success,

                "r2":

                    result.r2,

                "rmse":

                    result.rmse,

                "mae":

                    result.mae,

                "rss":

                    result.rss,

                "aic":

                    result.aic,

                "bic":

                    result.bic,

            }

        )

    return ranking


# ============================================================
# Certificate Panel
# ============================================================

def certificate_panel(
    summary,
):
    """
    Scientific certificate generated by selection.py.
    """

    return summary.get(

        "certificate",

        {}

    )


# ============================================================
# Dashboard Builder
# ============================================================

def build_dashboard(
    results,
):
    """
    Build complete experiment dashboard.
    """

    summary = selection_summary(

        results

    )

    best = summary.get(

        "best_model"

    )

    dashboard = {

        "metadata":

            build_metadata(),

        "experiment":

            experiment_panel(

                results

            ),

        "selection":

            selection_panel(

                results

            ),

        "best_model":

            best_model_panel(

                best

            ),

        "residuals":

            residual_panel(

                best

            ),

        "ranking":

            ranking_panel(

                results

            ),

        "certificate":

            certificate_panel(

                summary

            ),

    }

    return dashboard


# ============================================================
# Export
# ============================================================

def dashboard_to_dict(
    results,
):
    """
    Public dictionary representation.
    """

    return build_dashboard(

        results

    )


# ============================================================
# Public API
# ============================================================

__all__ = [

    "build_dashboard",

    "dashboard_to_dict",

    "build_metadata",

    "experiment_panel",

    "selection_panel",

    "best_model_panel",

    "residual_panel",

    "ranking_panel",

    "certificate_panel",

]
