#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
============================================================
GER
S29-E6.1
GLOBAL GEOMETRY SAMPLING
============================================================

Objective
---------
Perform a massive exploration of the admissible geometric
space generated by the GER engine.

Instead of analysing only the currently known regions,
this experiment generates a large number of admissible
geometries, extracts their signatures and builds a permanent
scientific database.

This experiment is cumulative.

Multiple executions extend the existing database instead of
restarting from zero.

Main goals
----------
• Sample the global geometric space.
• Build a permanent geometry database.
• Measure density of admissible geometries.
• Detect forbidden regions.
• Detect highly populated regions.
• Produce statistical maps.
• Supply data for S29-E6.2.
• Supply data for future GER experiments.

Outputs
-------

geometric_database/

    global_geometry_sampling/

        geometries.parquet
        signatures.parquet
        observables.parquet

        checkpoints/
        statistics/
        histograms/
        density_maps/
        logs/

Execution
---------
python GER_CORE/S29/S29_E6_1_global_geometry_sampling.py

Author
------
GER Project
"""

# ============================================================
# Imports
# ============================================================

import os
import sys
import json
import math
import random
import time
import shutil
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

from scipy.stats import entropy

from tqdm.auto import tqdm

# ============================================================
# Global Configuration
# ============================================================

RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

# ------------------------------------------------------------

TOTAL_GEOMETRIES = 2_000_000

SAVE_INTERVAL = 1000

CHECKPOINT_INTERVAL = 1000

STATISTICS_INTERVAL = 25000

LOG_INTERVAL = 100

# ------------------------------------------------------------

MIN_VERTICES = 8

MAX_VERTICES = 64

MIN_EDGES = 10

MAX_EDGES = 256

# ------------------------------------------------------------
# Persistent Storage
# ------------------------------------------------------------

RESULTS = Path(
    "/content/drive/MyDrive/GER_RESULTS"
)

if not RESULTS.exists():

    raise RuntimeError(

        "\nGoogle Drive not mounted.\n"
        "Mount Google Drive before running this experiment."

    )

DATABASE = RESULTS / "S29_E6.1"

CHECKPOINT_DIR = DATABASE / "checkpoints"

LOG_DIR = DATABASE / "logs"

STATISTICS_DIR = DATABASE / "statistics"

HISTOGRAM_DIR = DATABASE / "histograms"

DENSITY_DIR = DATABASE / "density_maps"

TMP_DIR = DATABASE / "tmp"

# ------------------------------------------------------------

GEOMETRIES_FILE = (
    DATABASE /
    "geometries.parquet"
)

SIGNATURES_FILE = (
    DATABASE /
    "signatures.parquet"
)

OBSERVABLES_FILE = (
    DATABASE /
    "observables.parquet"
)

CHECKPOINT_FILE = (
    CHECKPOINT_DIR /
    "sampling_checkpoint.json"
)

RUN_LOG = (
    LOG_DIR /
    "sampling.log"
)

# ============================================================
# Directory Initialization
# ============================================================

DIRECTORIES = [

    DATABASE,

    CHECKPOINT_DIR,

    LOG_DIR,

    STATISTICS_DIR,

    HISTOGRAM_DIR,

    DENSITY_DIR,

    TMP_DIR

]

for directory in DIRECTORIES:

    directory.mkdir(

        parents=True,

        exist_ok=True

    )

print("=" * 60)
print("Persistent Storage")
print("=" * 60)
print("[OK] Google Drive")
print(f"[OK] Output : {DATABASE}")
print("=" * 60)

# ============================================================
# Compact Logger
# ============================================================

class CompactLogger:

    def __init__(self):

        self.start_time = time.time()

        self.last_update = self.start_time

    def banner(self):

        print()

        print("=" * 60)
        print("GER S29-E6.1")
        print("GLOBAL GEOMETRY SAMPLING")
        print("=" * 60)
        print()

    def log(self, text):

        now = datetime.now()

        line = (
            f"[{now:%H:%M:%S}] {text}"
        )

        print(line)

        with open(
            RUN_LOG,
            "a",
            encoding="utf-8"
        ) as f:

            f.write(line + "\n")

    def progress(

        self,

        current,

        total,

        accepted,

        rejected,

        rate

    ):

        percent = 100 * current / total

        elapsed = time.time() - self.start_time

        remaining = (
            total - current
        )

        eta = (
            remaining / rate
            if rate > 0
            else 0
        )

        hours = int(eta // 3600)

        minutes = int(
            (eta % 3600) // 60
        )

        bar_size = 30

        filled = int(
            percent / 100 * bar_size
        )

        bar = (
            "█" * filled +
            "░" * (bar_size - filled)
        )

        print()

        print("=" * 60)

        print(
            f"Progress : "
            f"{current:,}/{total:,}"
        )

        print(
            f"[{bar}] "
            f"{percent:6.2f}%"
        )

        print()

        print(
            f"Accepted : {accepted:,}"
        )

        print(
            f"Rejected : {rejected:,}"
        )

        print(
            f"Speed    : {rate:,.0f} geom/s"
        )

        print(
            f"ETA      : "
            f"{hours:02d}:{minutes:02d}"
        )

        print("=" * 60)

# ============================================================
# Checkpoint Manager
# ============================================================

class CheckpointManager:

    def __init__(self):

        self.data = {

            "processed": 0,

            "accepted": 0,

            "rejected": 0,

            "database_size": 0,

            "last_update": None,

            "random_seed": RANDOM_SEED

        }

    def exists(self):

        return CHECKPOINT_FILE.exists()

    def load(self):

        if not self.exists():

            return

        with open(
            CHECKPOINT_FILE,
            "r",
            encoding="utf-8"
        ) as f:

            self.data = json.load(f)

    def save(self):

        self.data[
            "last_update"
        ] = str(datetime.now())

        with open(
            CHECKPOINT_FILE,
            "w",
            encoding="utf-8"
        ) as f:

            json.dump(

                self.data,

                f,

                indent=4

            )

# ============================================================
# Persistent Database
# ============================================================

class GeometryDatabase:

    """
    Permanent storage.

    New executions append new geometries.

    Existing geometries are preserved.
    """

    def __init__(self):

        self.geometries = []

        self.signatures = []

        self.observables = []

    def append_geometry(

        self,

        geometry,

        signature,

        observables

    ):

        self.geometries.append(
            geometry
        )

        self.signatures.append(
            signature
        )

        self.observables.append(
            observables
        )
          # --------------------------------------------------------

    def flush(self):

        if len(self.geometries):

            df = pd.DataFrame(
                self.geometries
            )

            if GEOMETRIES_FILE.exists():

                previous = pd.read_parquet(
                    GEOMETRIES_FILE
                )

                df = pd.concat(
                    [
                        previous,
                        df
                    ],
                    ignore_index=True
                )

            df.to_parquet(
                GEOMETRIES_FILE,
                index=False
            )

        # ----------------------------------------------------

        if len(self.signatures):

            df = pd.DataFrame(
                self.signatures
            )

            if SIGNATURES_FILE.exists():

                previous = pd.read_parquet(
                    SIGNATURES_FILE
                )

                df = pd.concat(
                    [
                        previous,
                        df
                    ],
                    ignore_index=True
                )

            df.to_parquet(
                SIGNATURES_FILE,
                index=False
            )

        # ----------------------------------------------------

        if len(self.observables):

            df = pd.DataFrame(
                self.observables
            )

            if OBSERVABLES_FILE.exists():

                previous = pd.read_parquet(
                    OBSERVABLES_FILE
                )

                df = pd.concat(
                    [
                        previous,
                        df
                    ],
                    ignore_index=True
                )

            df.to_parquet(
                OBSERVABLES_FILE,
                index=False
            )

        self.clear()

    # --------------------------------------------------------

    def clear(self):

        self.geometries.clear()

        self.signatures.clear()

        self.observables.clear()

# ============================================================
# Geometry Generator
# ============================================================

class GeometryGenerator:

    """
    Generates admissible random geometries.

    This class is intentionally isolated.

    Future versions may replace the random generator
    by the official GER engine without modifying the
    rest of the experiment.
    """

    def __init__(self):

        pass

    # --------------------------------------------------------

    def random_vertices(self):

        return random.randint(

            MIN_VERTICES,

            MAX_VERTICES

        )

    # --------------------------------------------------------

    def random_edges(self, n):

        maximum = min(

            MAX_EDGES,

            n * (n - 1) // 2

        )

        minimum = max(

            MIN_EDGES,

            n - 1

        )

        return random.randint(

            minimum,

            maximum

        )

    # --------------------------------------------------------

    def generate(self):

        vertices = self.random_vertices()

        edges = self.random_edges(vertices)

        geometry = {

            "vertices": vertices,

            "edges": edges,

            "density":

                edges /

                (vertices * (vertices - 1) / 2),

            "seed":

                random.randint(

                    0,

                    2**32 - 1

                )

        }

        return geometry

# ============================================================
# Signature Engine
# ============================================================

class SignatureEngine:

    """
    Converts a geometry into a GER signature.

    The implementation is intentionally modular.

    When the definitive GER engine is available,
    only this class needs to be replaced.
    """

    def __init__(self):

        pass

    # --------------------------------------------------------

    def compute(self, geometry):

        n = geometry["vertices"]

        e = geometry["edges"]

        density = geometry["density"]

        diameter = (

            math.log(n + 1)

            * (1.0 / density)

        )

        convergence = (

            density *

            np.sqrt(e)

        )

        recurrence = (

            abs(

                np.sin(

                    density * np.pi

                )

            )

        )

        harmonic = (

            1 /

            (1 + diameter)

        )

        return {

            "Diameter":

                diameter,

            "Convergence":

                convergence,

            "Recurrence":

                recurrence,

            "Harmonic":

                harmonic

        }

# ============================================================
# Observable Extraction
# ============================================================

class ObservableExtractor:

    """
    Computes all observables stored
    in the scientific database.
    """

    def __init__(self):

        pass

    # --------------------------------------------------------

    def extract(

        self,

        geometry,

        signature

    ):

        n = geometry["vertices"]

        e = geometry["edges"]

        density = geometry["density"]

        degree = (

            2 * e / n

        )

        weighted_degree = (

            degree *

            density

        )

        average_distance = (

            signature["Diameter"] /

            2

        )

        maximum_distance = (

            signature["Diameter"]

        )

        clustering = (

            density ** 2

        )

        entropy_value = entropy(

            [

                density,

                1 - density

            ]

        )

        return {

            "Vertices":

                n,

            "Edges":

                e,

            "Density":

                density,

            "Degree":

                degree,

            "WeightedDegree":

                weighted_degree,

            "AverageDistance":

                average_distance,

            "MaximumDistance":

                maximum_distance,

            "Diameter":

                signature["Diameter"],

            "Convergence":

                signature["Convergence"],

            "Recurrence":

                signature["Recurrence"],

            "Harmonic":

                signature["Harmonic"],

            "Clustering":

                clustering,

            "Entropy":

                entropy_value

        }

# ============================================================
# Geometry Validator
# ============================================================

class GeometryValidator:

    """
    Rejects invalid geometries.

    The acceptance criteria may evolve
    during future GER experiments.
    """

    def __init__(self):

        pass

    # --------------------------------------------------------

    def validate(

        self,

        geometry,

        signature,

        observables

    ):

        if geometry["vertices"] < 2:

            return False

        if geometry["edges"] < geometry["vertices"] - 1:

            return False

        if geometry["density"] <= 0:

            return False

        if geometry["density"] > 1:

            return False

        if signature["Diameter"] <= 0:

            return False

        if np.isnan(

            observables["Entropy"]

        ):

            return False

        return True
      # ============================================================
# Statistics Engine
# ============================================================

class StatisticsEngine:

    """
    Incremental statistical analysis of the sampled
    geometric space.
    """

    def __init__(self):

        self.observable_history = []

    # --------------------------------------------------------

    def update(self, observables):

        self.observable_history.append(
            observables
        )

    # --------------------------------------------------------

    def dataframe(self):

        if len(self.observable_history) == 0:

            return pd.DataFrame()

        return pd.DataFrame(
            self.observable_history
        )

    # --------------------------------------------------------

    def save_statistics(self):

        df = self.dataframe()

        if len(df) == 0:

            return

        summary = df.describe().T

        summary.to_csv(

            STATISTICS_DIR /
            "summary_statistics.csv"

        )

        correlation = df.corr(
            numeric_only=True
        )

        correlation.to_csv(

            STATISTICS_DIR /
            "correlation_matrix.csv"

        )

        covariance = df.cov(
            numeric_only=True
        )

        covariance.to_csv(

            STATISTICS_DIR /
            "covariance_matrix.csv"

        )

# ============================================================
# Density Estimator
# ============================================================

class DensityEstimator:

    """
    Estimates the occupation of the
    geometric space.
    """

    def __init__(self):

        self.points = []

    # --------------------------------------------------------

    def add(self, observables):

        self.points.append([

            observables["Diameter"],

            observables["Convergence"],

            observables["Recurrence"],

            observables["Density"]

        ])

    # --------------------------------------------------------

    def export(self):

        if len(self.points) == 0:

            return

        df = pd.DataFrame(

            self.points,

            columns=[

                "Diameter",

                "Convergence",

                "Recurrence",

                "Density"

            ]

        )

        df.to_parquet(

            DENSITY_DIR /
            "density_points.parquet",

            index=False

        )

# ============================================================
# Histogram Builder
# ============================================================

class HistogramBuilder:

    """
    Stores distributions that will later
    be transformed into publication-quality
    figures.
    """

    def __init__(self):

        self.data = []

    # --------------------------------------------------------

    def append(self, observables):

        self.data.append(
            observables
        )

    # --------------------------------------------------------

    def export(self):

        if len(self.data) == 0:

            return

        df = pd.DataFrame(
            self.data
        )

        for column in df.columns:

            values = np.histogram(

                df[column],

                bins=100

            )

            histogram = pd.DataFrame({

                "Left":
                    values[1][:-1],

                "Right":
                    values[1][1:],

                "Count":
                    values[0]

            })

            histogram.to_csv(

                HISTOGRAM_DIR /
                f"{column}.csv",

                index=False

            )

# ============================================================
# Sampling Engine
# ============================================================

class GlobalSampler:

    """
    Main controller of S29-E6.1.
    """

    def __init__(self):

        self.logger = CompactLogger()

        self.database = GeometryDatabase()

        self.generator = GeometryGenerator()

        self.signature_engine = SignatureEngine()

        self.extractor = ObservableExtractor()

        self.validator = GeometryValidator()

        self.statistics = StatisticsEngine()

        self.histograms = HistogramBuilder()

        self.density = DensityEstimator()

        self.checkpoint = CheckpointManager()

        if self.checkpoint.exists():

            self.checkpoint.load()

            self.logger.log(
                "Checkpoint restored."
            )

        self.processed = self.checkpoint.data[
            "processed"
        ]

        self.accepted = self.checkpoint.data[
            "accepted"
        ]

        self.rejected = self.checkpoint.data[
            "rejected"
        ]

        self.start_clock = time.time()

    # --------------------------------------------------------

    def speed(self):

        elapsed = max(

            time.time() -
            self.start_clock,

            1e-9

        )

        return self.processed / elapsed

    # --------------------------------------------------------

    def checkpoint_save(self):

        self.checkpoint.data[
            "processed"
        ] = self.processed

        self.checkpoint.data[
            "accepted"
        ] = self.accepted

        self.checkpoint.data[
            "rejected"
        ] = self.rejected

        self.checkpoint.data[
            "database_size"
        ] = self.accepted

        self.checkpoint.save()
          # --------------------------------------------------------

    def flush(self):

        self.database.flush()

        self.statistics.save_statistics()

        self.histograms.export()

        self.density.export()

    # --------------------------------------------------------

    def process_one_geometry(self):

        geometry = self.generator.generate()

        signature = self.signature_engine.compute(
            geometry
        )

        observables = self.extractor.extract(

            geometry,

            signature

        )

        valid = self.validator.validate(

            geometry,

            signature,

            observables

        )

        self.processed += 1

        if not valid:

            self.rejected += 1

            return

        self.accepted += 1

        self.database.append_geometry(

            geometry,

            signature,

            observables

        )

        self.statistics.update(
            observables
        )

        self.histograms.append(
            observables
        )

        self.density.add(
            observables
        )

    # --------------------------------------------------------

    def run(self):

        self.logger.banner()

        self.logger.log(
            f"Target geometries : {TOTAL_GEOMETRIES:,}"
        )

        self.logger.log(
            f"Checkpoint start  : {self.processed:,}"
        )

        while self.processed < TOTAL_GEOMETRIES:

            self.process_one_geometry()

            # --------------------------------------------

            if (
                self.accepted > 0
                and
                self.accepted % SAVE_INTERVAL == 0
            ):

                self.flush()

            # --------------------------------------------

            if (
                self.processed > 0
                and
                self.processed % CHECKPOINT_INTERVAL == 0
            ):

                self.checkpoint_save()

            # --------------------------------------------

            if (
                self.processed > 0
                and
                self.processed % STATISTICS_INTERVAL == 0
            ):

                self.statistics.save_statistics()

            # --------------------------------------------

            if (
                self.processed > 0
                and
                self.processed % LOG_INTERVAL == 0
            ):

                self.logger.progress(

                    self.processed,

                    TOTAL_GEOMETRIES,

                    self.accepted,

                    self.rejected,

                    self.speed()

                )

        # ------------------------------------------------

        self.flush()

        self.checkpoint_save()

        self.finish()

    # --------------------------------------------------------

    def finish(self):

        elapsed = time.time() - self.start_clock

        print()

        print("=" * 60)
        print("GLOBAL GEOMETRY SAMPLING FINISHED")
        print("=" * 60)

        print()

        print(f"Processed : {self.processed:,}")
        print(f"Accepted  : {self.accepted:,}")
        print(f"Rejected  : {self.rejected:,}")

        print()

        print(
            f"Elapsed   : {elapsed/3600:.2f} hours"
        )

        print(
            f"Average Speed : "
            f"{self.processed/max(elapsed,1):,.1f} geom/s"
        )

        print()

        print("Database")

        print(" ", GEOMETRIES_FILE)
        print(" ", SIGNATURES_FILE)
        print(" ", OBSERVABLES_FILE)

        print()

        print("Statistics")

        print(" ", STATISTICS_DIR)

        print()

        print("Histograms")

        print(" ", HISTOGRAM_DIR)

        print()

        print("Density Maps")

        print(" ", DENSITY_DIR)

        print()

        print("Logs")

        print(" ", LOG_DIR)

        print()

# ============================================================
# Main
# ============================================================

def main():

    sampler = GlobalSampler()

    sampler.run()

# ============================================================

if __name__ == "__main__":

    main()

# ============================================================
# END
# ============================================================
