# =====================================================================
# GER_CORE/S29/S29_E4_3_structural_backbone_analysis.py
# =====================================================================
#
# Project : GER — Geometria Espectral Relacional
#
# Experiment : S29-E4.3
#
# Title
# -----
# Structural Backbone Analysis
#
# Objective
# ---------
# Perform a quantitative structural analysis of the backbone graphs
# generated by S29-E4.2.
#
# Analyses
# --------
#
# 1. MST edge statistics
# 2. Hierarchical ordering
# 3. Critical links
# 4. Local geometry
# 5. Global geometry
# 6. Backbone comparison
#
# =====================================================================

import os
import json
import math

import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt


# =====================================================================
# CONFIGURATION
# =====================================================================

INPUT_DIR = "/content/drive/MyDrive/GER_RESULTS/S29_E4.2"

RESULTS_DIR = "/content/drive/MyDrive/GER_RESULTS/S29_E4.3"

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

BACKBONES = {

    "mst":
        "mst.graphml",

    "knn":
        "knn.graphml",

    "threshold":
        "threshold.graphml",

    "consensus":
        "consensus.graphml"

}


# =====================================================================
# LOAD GRAPH
# =====================================================================

def load_graph(filename):

    graph = nx.read_graphml(

        os.path.join(

            INPUT_DIR,

            filename

        )

    )

    for _, _, edge in graph.edges(data=True):

        edge["weight"] = float(

            edge["weight"]

        )

        edge["distance"] = float(

            edge["distance"]

        )

    return graph


# =====================================================================
# LOAD ALL
# =====================================================================

def load_backbones():

    graphs = {}

    for name, file in BACKBONES.items():

        graphs[name] = load_graph(file)

    return graphs


# =====================================================================
# EDGE WEIGHTS
# =====================================================================

def edge_weights(graph):

    return [

        graph[u][v]["weight"]

        for u, v in graph.edges()

    ]


# =====================================================================
# MST STATISTICS
# =====================================================================

def mst_statistics(graph):

    weights = sorted(

        edge_weights(graph)

    )

    dataframe = pd.Series(weights)

    stats = {

        "edges":

            len(weights),

        "minimum":

            float(dataframe.min()),

        "maximum":

            float(dataframe.max()),

        "mean":

            float(dataframe.mean()),

        "median":

            float(dataframe.median()),

        "std":

            float(dataframe.std()),

        "variance":

            float(dataframe.var()),

        "coefficient_variation":

            float(

                dataframe.std()

                /

                dataframe.mean()

            ),

        "total_length":

            float(

                dataframe.sum()

            ),

        "max_min_ratio":

            float(

                dataframe.max()

                /

                dataframe.min()

            )

    }

    return stats


# =====================================================================
# EDGE TABLE
# =====================================================================

def mst_edge_table(graph):

    rows = []

    for u, v, edge in graph.edges(data=True):

        rows.append(

            {

                "Source": u,

                "Target": v,

                "Distance":

                    edge["weight"]

            }

        )

    dataframe = pd.DataFrame(rows)

    dataframe.sort_values(

        "Distance",

        inplace=True

    )

    dataframe.reset_index(

        drop=True,

        inplace=True

    )

    return dataframe


# =====================================================================
# HISTOGRAM
# =====================================================================

def histogram(graph):

    plt.figure(

        figsize=(8,5)

    )

    plt.hist(

        edge_weights(graph),

        bins=10

    )

    plt.xlabel(

        "Edge Distance"

    )

    plt.ylabel(

        "Frequency"

    )

    plt.title(

        "MST Edge Distribution"

    )

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            RESULTS_DIR,

            "mst_weight_histogram.png"

        ),

        dpi=300

    )

    plt.close()


# =====================================================================
# RANK CURVE
# =====================================================================

def rank_curve(graph):

    weights = sorted(

        edge_weights(graph)

    )

    plt.figure(

        figsize=(8,5)

    )

    plt.plot(

        range(

            1,

            len(weights)+1

        ),

        weights,

        marker="o"

    )

    plt.xlabel(

        "Rank"

    )

    plt.ylabel(

        "Distance"

    )

    plt.title(

        "Ordered MST Edges"

    )

    plt.grid(True)

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            RESULTS_DIR,

            "mst_rank_curve.png"

        ),

        dpi=300

    )

    plt.close()
  # =====================================================================
# HIERARCHICAL STRUCTURE
# =====================================================================

def hierarchy_analysis(graph):

    table = mst_edge_table(graph)

    hierarchy = []

    cumulative = 0.0

    for level, row in table.iterrows():

        cumulative += row["Distance"]

        hierarchy.append(

            {

                "Level": level + 1,

                "Source": row["Source"],

                "Target": row["Target"],

                "Distance": row["Distance"],

                "CumulativeDistance": cumulative

            }

        )

    return pd.DataFrame(hierarchy)


# =====================================================================
# HIERARCHY TREE
# =====================================================================

def hierarchy_tree(graph):

    position = nx.spring_layout(

        graph,

        seed=42,

        weight="weight"

    )

    plt.figure(

        figsize=(10,8)

    )

    nx.draw_networkx_nodes(

        graph,

        position,

        node_size=900

    )

    nx.draw_networkx_edges(

        graph,

        position,

        width=2.5

    )

    nx.draw_networkx_labels(

        graph,

        position,

        font_weight="bold"

    )

    plt.title(

        "Hierarchical MST"

    )

    plt.axis("off")

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            RESULTS_DIR,

            "hierarchy_tree.png"

        ),

        dpi=300

    )

    plt.close()


# =====================================================================
# CRITICAL LINKS
# =====================================================================

def critical_links(graph):

    edge_between = nx.edge_betweenness_centrality(

        graph,

        weight="weight"

    )

    bridges = list(

        nx.bridges(graph)

    )

    rows = []

    for u, v, edge in graph.edges(data=True):

        rows.append(

            {

                "Source": u,

                "Target": v,

                "Distance": edge["weight"],

                "EdgeBetweenness":

                    edge_between[(u, v)],

                "Bridge":

                    (u, v) in bridges

            }

        )

    dataframe = pd.DataFrame(rows)

    dataframe.sort_values(

        "EdgeBetweenness",

        ascending=False,

        inplace=True

    )

    dataframe.reset_index(

        drop=True,

        inplace=True

    )

    return dataframe


# =====================================================================
# LOCAL GEOMETRY
# =====================================================================

def local_geometry(graph):

    rows = []

    for node in graph.nodes():

        distances = [

            graph[node][neighbor]["weight"]

            for neighbor

            in graph.neighbors(node)

        ]

        if len(distances) == 0:

            minimum = 0.0

            maximum = 0.0

            mean = 0.0

        else:

            minimum = min(distances)

            maximum = max(distances)

            mean = sum(distances) / len(distances)

        rows.append(

            {

                "Region": node,

                "Degree":

                    graph.degree(node),

                "WeightedDegree":

                    graph.degree(

                        node,

                        weight="weight"

                    ),

                "MinimumDistance":

                    minimum,

                "MaximumDistance":

                    maximum,

                "AverageDistance":

                    mean

            }

        )

    dataframe = pd.DataFrame(rows)

    dataframe.sort_values(

        "AverageDistance",

        inplace=True

    )

    dataframe.reset_index(

        drop=True,

        inplace=True

    )

    return dataframe


# =====================================================================
# GLOBAL GEOMETRY
# =====================================================================

def global_geometry(graph):

    report = {}

    report["nodes"] = graph.number_of_nodes()

    report["edges"] = graph.number_of_edges()

    report["density"] = nx.density(graph)

    report["connected"] = nx.is_connected(graph)

    report["average_degree"] = (

        sum(

            dict(

                graph.degree()

            ).values()

        )

        /

        graph.number_of_nodes()

    )

    if nx.is_connected(graph):

        report["diameter"] = nx.diameter(graph)

        report["radius"] = nx.radius(graph)

        report["average_path_length"] = (

            nx.average_shortest_path_length(

                graph,

                weight="weight"

            )

        )

        report["center"] = nx.center(graph)

        report["periphery"] = nx.periphery(graph)

        report["efficiency"] = nx.global_efficiency(graph)

    else:

        report["diameter"] = None

        report["radius"] = None

        report["average_path_length"] = None

        report["center"] = []

        report["periphery"] = []

        report["efficiency"] = None

    try:

        report["assortativity"] = (

            nx.degree_assortativity_coefficient(

                graph

            )

        )

    except Exception:

        report["assortativity"] = None

    return report


# =====================================================================
# CRITICAL EDGE FIGURE
# =====================================================================

def critical_edges_plot(

    graph,

    critical_table

):

    position = nx.spring_layout(

        graph,

        seed=42,

        weight="weight"

    )

    plt.figure(

        figsize=(10,8)

    )

    nx.draw_networkx_nodes(

        graph,

        position,

        node_size=900

    )

    nx.draw_networkx_labels(

        graph,

        position,

        font_weight="bold"

    )

    top = critical_table.head(3)

    highlighted = [

        (

            row["Source"],

            row["Target"]

        )

        for _, row

        in top.iterrows()

    ]

    normal = [

        edge

        for edge

        in graph.edges()

        if edge not in highlighted

        and (edge[1], edge[0])

        not in highlighted

    ]

    nx.draw_networkx_edges(

        graph,

        position,

        edgelist=normal,

        width=1.5

    )

    nx.draw_networkx_edges(

        graph,

        position,

        edgelist=highlighted,

        width=4.5

    )

    plt.title(

        "Critical Structural Links"

    )

    plt.axis("off")

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            RESULTS_DIR,

            "critical_edges.png"

        ),

        dpi=300

    )

    plt.close()
  # =====================================================================
# BACKBONE COMPARISON
# =====================================================================

def compare_backbones(graphs):

    rows = []

    for name, graph in graphs.items():

        weights = edge_weights(graph)

        row = {

            "Backbone": name,
            "Nodes": graph.number_of_nodes(),
            "Edges": graph.number_of_edges(),
            "Density": nx.density(graph),
            "Connected": nx.is_connected(graph),
            "AverageDegree":
                sum(dict(graph.degree()).values())
                /
                graph.number_of_nodes(),
            "AverageWeight":
                sum(weights) / len(weights)
                if len(weights) > 0 else 0.0,
            "MinimumWeight":
                min(weights)
                if len(weights) > 0 else 0.0,
            "MaximumWeight":
                max(weights)
                if len(weights) > 0 else 0.0
        }

        if nx.is_connected(graph):

            row["Diameter"] = nx.diameter(graph)

            row["AveragePath"] = nx.average_shortest_path_length(

                graph,

                weight="weight"

            )

            row["Efficiency"] = nx.global_efficiency(graph)

        else:

            row["Diameter"] = None
            row["AveragePath"] = None
            row["Efficiency"] = None

        rows.append(row)

    dataframe = pd.DataFrame(rows)

    return dataframe


# =====================================================================
# COMPARISON FIGURE
# =====================================================================

def comparison_plot(comparison):

    plt.figure(figsize=(8,5))

    plt.bar(

        comparison["Backbone"],

        comparison["Edges"]

    )

    plt.ylabel("Edges")

    plt.title("Backbone Comparison")

    plt.tight_layout()

    plt.savefig(

        os.path.join(

            RESULTS_DIR,

            "backbone_comparison.png"

        ),

        dpi=300

    )

    plt.close()


# =====================================================================
# SAVE REPORTS
# =====================================================================

def save_json(filename, obj):

    with open(

        os.path.join(

            RESULTS_DIR,

            filename

        ),

        "w",

        encoding="utf-8"

    ) as f:

        json.dump(

            obj,

            f,

            indent=4

        )


# =====================================================================
# MAIN
# =====================================================================

def main():

    print("="*70)
    print("GER")
    print("S29-E4.3")
    print("STRUCTURAL BACKBONE ANALYSIS")
    print("="*70)
    print()

    graphs = load_backbones()

    mst = graphs["mst"]

    print(

        "Loaded backbones:",

        ", ".join(graphs.keys())

    )

    print()

    mst_stats = mst_statistics(mst)

    mst_edges = mst_edge_table(mst)

    hierarchy = hierarchy_analysis(mst)

    critical = critical_links(mst)

    local = local_geometry(mst)

    histogram(mst)

    rank_curve(mst)

    hierarchy_tree(mst)

    critical_edges_plot(

        mst,

        critical

    )

    comparison = compare_backbones(

        graphs

    )

    comparison_plot(

        comparison

    )

    global_reports = {}

    for name, graph in graphs.items():

        global_reports[name] = global_geometry(

            graph

        )

    mst_edges.to_csv(

        os.path.join(

            RESULTS_DIR,

            "mst_edges.csv"

        ),

        index=False

    )

    hierarchy.to_csv(

        os.path.join(

            RESULTS_DIR,

            "hierarchy.csv"

        ),

        index=False

    )

    critical.to_csv(

        os.path.join(

            RESULTS_DIR,

            "critical_links.csv"

        ),

        index=False

    )

    local.to_csv(

        os.path.join(

            RESULTS_DIR,

            "local_geometry.csv"

        ),

        index=False

    )

    comparison.to_csv(

        os.path.join(

            RESULTS_DIR,

            "comparison.csv"

        ),

        index=False

    )

    save_json(

        "mst_statistics.json",

        mst_stats

    )

    save_json(

        "global_geometry.json",

        global_reports

    )

    print("MST edges             :", len(mst_edges))
    print("Hierarchy levels      :", len(hierarchy))
    print("Critical links        :", len(critical))
    print("Regions analyzed      :", len(local))
    print()

    print("Results saved to:")

    print(RESULTS_DIR)

    print()

    print("="*70)


# =====================================================================
# ENTRY POINT
# =====================================================================

if __name__ == "__main__":

    main()
