"""
============================================================
GER
L1.2 Signature Degeneracy Observatory
============================================================

Scientific Question
-------------------
How degenerate is the Relational Signature Space?

This observatory measures the intrinsic multiplicity of
geometric signatures generated by the GER engine.

Outputs
-------
report/
    signature_degeneracy_report.txt

tables/
    unique_signatures.csv
    multiplicity_distribution.csv
    top_signatures.csv

json/
    signature_degeneracy.json

certificate/
    certificate.json

Author
------
Eduardo Batista de Freitas

Framework
---------
GER

Version
-------
1.0
============================================================
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd

from GER.CORE.ger_storage import ExperimentStorage

from ...io import load_signatures


TITLE = "GER\nL1.2 Signature Degeneracy Observatory"


# ============================================================
# ANALYSIS
# ============================================================

def analyse(df: pd.DataFrame) -> dict:
    """
    Analyse signature degeneracy.
    """

    total_signatures = len(df)

    grouped = (
        df.groupby(list(df.columns))
        .size()
        .reset_index(name="Multiplicity")
        .sort_values("Multiplicity", ascending=False)
        .reset_index(drop=True)
    )

    unique_signatures = len(grouped)

    multiplicities = grouped["Multiplicity"].to_numpy()

    uniqueness_rate = (
        100.0 * unique_signatures / total_signatures
        if total_signatures
        else 0.0
    )

    degeneracy_rate = 100.0 - uniqueness_rate

    probabilities = multiplicities / multiplicities.sum()

    entropy = float(
        -np.sum(probabilities * np.log2(probabilities))
    )

    distribution = (
        grouped["Multiplicity"]
        .value_counts()
        .sort_index()
        .rename_axis("Multiplicity")
        .reset_index(name="Count")
    )

    top20 = grouped.head(20).copy()

    top20["Percentage"] = (
        100.0
        * top20["Multiplicity"]
        / total_signatures
    )

    summary = {

        "total_signatures": int(total_signatures),

        "unique_signatures": int(unique_signatures),

        "uniqueness_rate_percent": float(
            uniqueness_rate
        ),

        "degeneracy_rate_percent": float(
            degeneracy_rate
        ),

        "minimum_multiplicity": int(
            multiplicities.min()
        ),

        "maximum_multiplicity": int(
            multiplicities.max()
        ),

        "mean_multiplicity": float(
            multiplicities.mean()
        ),

        "median_multiplicity": float(
            np.median(multiplicities)
        ),

        "std_multiplicity": float(
            multiplicities.std()
        ),

        "entropy_bits": float(entropy),

        "status": "PASS",

    }

    return {

        "summary": summary,

        "unique_signatures": grouped,

        "distribution": distribution,

        "top20": top20,

  }
  # ============================================================
# SAVE
# ============================================================

def save(storage: ExperimentStorage, result: dict) -> None:

    summary = result["summary"]

    storage.create_folder("report")
    storage.create_folder("tables")
    storage.create_folder("json")
    storage.create_folder("certificate")

    report_folder = storage.folder("report")
    tables_folder = storage.folder("tables")
    json_folder = storage.folder("json")
    certificate_folder = storage.folder("certificate")

    # --------------------------------------------------------
    # TABLES
    # --------------------------------------------------------

    result["unique_signatures"].to_csv(
        tables_folder / "unique_signatures.csv",
        index=False,
    )

    result["distribution"].to_csv(
        tables_folder / "multiplicity_distribution.csv",
        index=False,
    )

    result["top20"].to_csv(
        tables_folder / "top_signatures.csv",
        index=False,
    )

    # --------------------------------------------------------
    # JSON
    # --------------------------------------------------------

    with open(
        json_folder / "signature_degeneracy.json",
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            summary,
            f,
            indent=4,
        )

    # --------------------------------------------------------
    # CERTIFICATE
    # --------------------------------------------------------

    with open(
        certificate_folder / "certificate.json",
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            {
                "observatory": "L1.2",
                "title": "Signature Degeneracy Observatory",
                "status": summary["status"],
            },
            f,
            indent=4,
        )

    # --------------------------------------------------------
    # REPORT
    # --------------------------------------------------------

    report = f"""
============================================================
GER
L1.2 Signature Degeneracy Observatory
============================================================

Total Signatures
{summary['total_signatures']}

Unique Signatures
{summary['unique_signatures']}

Uniqueness (%)
{summary['uniqueness_rate_percent']:.6f}

Degeneracy (%)
{summary['degeneracy_rate_percent']:.6f}

Minimum Multiplicity
{summary['minimum_multiplicity']}

Maximum Multiplicity
{summary['maximum_multiplicity']}

Mean Multiplicity
{summary['mean_multiplicity']:.6f}

Median Multiplicity
{summary['median_multiplicity']:.6f}

Standard Deviation
{summary['std_multiplicity']:.6f}

Entropy (bits)
{summary['entropy_bits']:.6f}

Status
{summary['status']}

============================================================
"""

    with open(
        report_folder / "signature_degeneracy_report.txt",
        "w",
        encoding="utf-8",
    ) as f:

        f.write(report)

    print(report)


# ============================================================
# MAIN
# ============================================================

def run():

    storage = ExperimentStorage(

        experiment="S29_E6_2_L1_2",

        folders=[

            "report",

            "tables",

            "json",

            "certificate",

        ],

    )

    print("=" * 60)
    print(TITLE)
    print("=" * 60)

    df = load_signatures()

    result = analyse(df)

    save(storage, result)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    run()
