"""
=============================================================
S29_E10_1_4_FAMILY1_VALIDATION.py
=============================================================

Part 1
-------

Load and validate all artifacts generated by:

    E10.1.1
    E10.1.2
    E10.1.3

No scientific analysis is performed in this stage.

=============================================================
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


# ============================================================
# ROOT
# ============================================================

RESULTS_ROOT = Path(
    "/content/drive/MyDrive/GER_RESULTS/S29/E10"
)

OUTPUT_DIR = (
    RESULTS_ROOT
    / "E10_1_4_Family1Validation"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# INPUT FILES
# ============================================================

FILES = {

    # --------------------------------------------------------
    # E10.1.1
    # --------------------------------------------------------

    "signature":

        RESULTS_ROOT
        / "E10_1_1"
        / "signature_surface.parquet",

    "certificate":

        RESULTS_ROOT
        / "E10_1_1"
        / "certificate_surface.parquet",

    "grid":

        RESULTS_ROOT
        / "E10_1_1"
        / "grid.parquet",

    # --------------------------------------------------------
    # E10.1.2
    # --------------------------------------------------------

    "gradient":

        RESULTS_ROOT
        / "E10_1_2_A_Gradient"
        / "gradient_surface.parquet",

    "continuity":

        RESULTS_ROOT
        / "E10_1_2_B_Continuity"
        / "continuity_surface.parquet",

    "boundaries":

        RESULTS_ROOT
        / "E10_1_2_C_Boundaries"
        / "boundary_surface.parquet",

    "connected_regions":

        RESULTS_ROOT
        / "E10_1_2_D_ConnectedRegions"
        / "connected_regions.parquet",

    "effective_dimension":

        RESULTS_ROOT
        / "E10_1_2_E_Dimension"
        / "effective_dimension.parquet",

    # --------------------------------------------------------
    # E10.1.3
    # --------------------------------------------------------

    "perturbation":

        RESULTS_ROOT
        / "E10_1_3_A_PerturbationCalibration"
        / "perturbation_calibration.parquet",

    "response":

        RESULTS_ROOT
        / "E10_1_3_B_ResponseField"
        / "response_field.parquet",

    "propagation":

        RESULTS_ROOT
        / "E10_1_3_C_PropagationAnalysis"
        / "propagation_analysis.parquet",

    "stability":

        RESULTS_ROOT
        / "E10_1_3_D_StabilityMap"
        / "stability_map.parquet",

    "atlas":

        RESULTS_ROOT
        / "E10_1_3_E_ResponseAtlas"
        / "response_atlas.parquet",
}


# ============================================================
# LOADER
# ============================================================

datasets = {}

print("\n" + "=" * 80)
print("E10.1.4 - FAMILY 1 VALIDATION")
print("=" * 80)

print("\nLoading datasets...\n")

for name, file in FILES.items():

    print(f"{name:<24}", end="")

    if not file.exists():

        raise FileNotFoundError(file)

    df = pd.read_parquet(file)

    datasets[name] = df

    print(df.shape)


# ============================================================
# INVENTORY
# ============================================================

inventory = []

for name, df in datasets.items():

    inventory.append({

        "dataset": name,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),

    })

inventory = pd.DataFrame(inventory)

inventory.to_csv(

    OUTPUT_DIR / "dataset_inventory.csv",

    index=False,

)


# ============================================================
# METADATA
# ============================================================

metadata = {

    "experiment": "E10.1.4",

    "title": "Family 1 Validation",

    "datasets": list(datasets.keys()),

}

with open(

    OUTPUT_DIR / "metadata.json",

    "w",

) as f:

    json.dump(

        metadata,

        f,

        indent=4,

    )


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("DATASETS")
print("=" * 80)

print(inventory)

print("\nPart 1 completed.")

# ============================================================
# PART 2
# STATISTICAL VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("PART 2 - STATISTICAL VALIDATION")
print("=" * 80)

statistics = []

for name, df in datasets.items():

    print(f"\n{name}")
    print("-" * 60)

    rows = int(df.shape[0])
    cols = int(df.shape[1])

    nulls = int(df.isnull().sum().sum())

    duplicated = int(df.duplicated().sum())

    numeric = df.select_dtypes(include="number")

    if len(numeric.columns):

        unique_values = int(
            numeric.nunique().sum()
        )

        variance = float(
            numeric.var().sum()
        )

    else:

        unique_values = 0
        variance = 0.0

    print(f"Rows ............ {rows}")
    print(f"Columns ......... {cols}")
    print(f"Null values ..... {nulls}")
    print(f"Duplicates ...... {duplicated}")
    print(f"Numeric columns . {len(numeric.columns)}")
    print(f"Total variance .. {variance:.6f}")

    statistics.append({

        "dataset": name,

        "rows": rows,

        "columns": cols,

        "null_values": nulls,

        "duplicates": duplicated,

        "numeric_columns": len(numeric.columns),

        "unique_numeric_values": unique_values,

        "total_variance": variance,

        "valid":

            (
                rows > 0
                and
                duplicated == 0
                and
                nulls == 0
            ),

    })


statistics = pd.DataFrame(statistics)

statistics.to_csv(

    OUTPUT_DIR / "statistical_validation.csv",

    index=False,

)


# ============================================================
# GLOBAL SUMMARY
# ============================================================

summary = {

    "datasets": len(statistics),

    "valid":

        bool(statistics["valid"].all()),

    "datasets_without_nulls":

        int((statistics.null_values == 0).sum()),

    "datasets_without_duplicates":

        int((statistics.duplicates == 0).sum()),

    "datasets_with_variation":

        int(
            (statistics.total_variance > 0).sum()
        ),

}

with open(

    OUTPUT_DIR / "statistical_summary.json",

    "w",

) as f:

    json.dump(

        summary,

        f,

        indent=4,

    )


print("\n" + "=" * 80)
print("STATISTICAL SUMMARY")
print("=" * 80)

print(statistics)

print("\nGlobal summary")

for k, v in summary.items():
    print(f"{k:30} {v}")

print("\nPart 2 completed.")

# ============================================================
# PART 3
# FAMILY 1 VALIDATION
# ============================================================

print("\n" + "=" * 80)
print("PART 3 - FAMILY 1 VALIDATION")
print("=" * 80)

signature = datasets["signature"]

validation = {}

# ------------------------------------------------------------
# Grid integrity
# ------------------------------------------------------------

validation["grid_complete"] = (

    signature.gamma.nunique() > 1

)

validation["omega_present"] = (

    "omega" in signature.columns

)

validation["expected_points"] = len(signature)

validation["gamma_levels"] = int(

    signature.gamma.nunique()

)

validation["omega_levels"] = int(

    signature.omega.nunique()

)

# ------------------------------------------------------------
# Observable variation
# ------------------------------------------------------------

observables = [

    "diameter",
    "convergence",
    "recurrence",
    "drift",

]

variation = []

for observable in observables:

    values = signature.groupby(

        "gamma"

    )[observable].mean()

    amplitude = float(

        values.max() - values.min()

    )

    monotonic = bool(

        values.is_monotonic_increasing
        or
        values.is_monotonic_decreasing

    )

    variation.append({

        "observable": observable,

        "minimum": float(values.min()),

        "maximum": float(values.max()),

        "amplitude": amplitude,

        "monotonic": monotonic,

        "varying": amplitude > 0,

    })

variation = pd.DataFrame(variation)

variation.to_csv(

    OUTPUT_DIR /
    "family1_variation.csv",

    index=False,

)

# ------------------------------------------------------------
# Omega neutrality
# ------------------------------------------------------------

omega_validation = []

for observable in observables:

    values = signature.groupby(

        "omega"

    )[observable].mean()

    amplitude = float(

        values.max() - values.min()

    )

    omega_validation.append({

        "observable": observable,

        "variation": amplitude,

        "neutral":

            amplitude < 1e-12,

    })

omega_validation = pd.DataFrame(

    omega_validation

)

omega_validation.to_csv(

    OUTPUT_DIR /
    "omega_neutrality.csv",

    index=False,

)

# ------------------------------------------------------------
# Final criteria
# ------------------------------------------------------------

criteria = {

    "gamma_generates_variation":

        bool(
            variation["varying"].all()
        ),

    "omega_is_neutral":

        bool(
            omega_validation["neutral"].all()
        ),

    "family1_consistent":

        bool(
            variation["varying"].all()
            and
            omega_validation["neutral"].all()
        ),

}

with open(

    OUTPUT_DIR /
    "family1_validation.json",

    "w",

) as f:

    json.dump(

        criteria,

        f,

        indent=4,

    )

# ------------------------------------------------------------
# Console
# ------------------------------------------------------------

print("\nObservable variation")
print(variation)

print("\nOmega neutrality")
print(omega_validation)

print("\nValidation")

for key, value in criteria.items():

    print(f"{key:30} {value}")

print("\nPart 3 completed.")

# ============================================================
# PART 4
# FINAL CERTIFICATE
# ============================================================

print("\n" + "=" * 80)
print("PART 4 - FINAL CERTIFICATE")
print("=" * 80)

certificate = {}

# ------------------------------------------------------------
# Dataset integrity
# ------------------------------------------------------------

certificate["datasets_loaded"] = len(datasets)

certificate["all_datasets_valid"] = bool(
    statistics["valid"].all()
)

certificate["datasets"] = list(datasets.keys())

# ------------------------------------------------------------
# Family 1 validation
# ------------------------------------------------------------

certificate["family"] = "Family 1"

certificate["operator"] = "U(gamma) = (1 + gamma) I"

certificate["omega_status"] = "Reserved"

certificate["gamma_generates_variation"] = criteria[
    "gamma_generates_variation"
]

certificate["omega_is_neutral"] = criteria[
    "omega_is_neutral"
]

certificate["family_validated"] = criteria[
    "family1_consistent"
]

# ------------------------------------------------------------
# Observable summary
# ------------------------------------------------------------

observable_summary = []

for _, row in variation.iterrows():

    observable_summary.append({

        "observable": row["observable"],

        "minimum": float(row["minimum"]),

        "maximum": float(row["maximum"]),

        "amplitude": float(row["amplitude"]),

        "monotonic": bool(row["monotonic"]),

    })

certificate["observables"] = observable_summary

# ------------------------------------------------------------
# Decision
# ------------------------------------------------------------

if certificate["family_validated"]:

    decision = (
        "APPROVED - "
        "Family 1 satisfies the E10-v1 admissibility "
        "criteria."
    )

else:

    decision = (
        "NOT APPROVED - "
        "One or more admissibility criteria failed."
    )

certificate["decision"] = decision

# ------------------------------------------------------------
# Save JSON
# ------------------------------------------------------------

with open(

    OUTPUT_DIR /
    "family1_certificate.json",

    "w",

) as f:

    json.dump(

        certificate,

        f,

        indent=4,

    )

# ------------------------------------------------------------
# Save TXT
# ------------------------------------------------------------

report = []

report.append("=" * 70)
report.append("E10.1.4 - FAMILY 1 VALIDATION CERTIFICATE")
report.append("=" * 70)
report.append("")

report.append(f"Datasets loaded : {certificate['datasets_loaded']}")
report.append(
    f"Datasets valid  : {certificate['all_datasets_valid']}"
)
report.append("")
report.append(f"Operator        : {certificate['operator']}")
report.append(f"Omega           : {certificate['omega_status']}")
report.append("")
report.append(
    f"Gamma variation : "
    f"{certificate['gamma_generates_variation']}"
)
report.append(
    f"Omega neutrality: "
    f"{certificate['omega_is_neutral']}"
)
report.append("")
report.append("Observable summary")
report.append("------------------")

for obs in observable_summary:

    report.append(

        f"{obs['observable']:15}"
        f" amplitude={obs['amplitude']:.6f}"
        f" monotonic={obs['monotonic']}"

    )

report.append("")
report.append("Decision")
report.append("--------")
report.append(decision)
report.append("")
report.append("=" * 70)

with open(

    OUTPUT_DIR /
    "family1_certificate.txt",

    "w",

) as f:

    f.write("\n".join(report))

# ------------------------------------------------------------
# Console
# ------------------------------------------------------------

print()

for line in report:
    print(line)

print("\nPart 4 completed.")

print("\n" + "=" * 80)
print("E10.1.4 FINISHED")
print("=" * 80)
print(f"\nResults saved to:\n{OUTPUT_DIR}")

# ============================================================
# PART 5
# CAMPAIGN MANIFEST
# ============================================================

from datetime import datetime
import json

print("\n" + "=" * 80)
print("PART 5 - CAMPAIGN MANIFEST")
print("=" * 80)

# ------------------------------------------------------------
# Manifest
# ------------------------------------------------------------

manifest = {

    "experiment": "E10.1.4",

    "title": "Family 1 Validation",

    "status": "FINISHED",

    "created_at": datetime.utcnow().isoformat(),

    "output_directory": str(OUTPUT_DIR),

    "datasets": list(datasets.keys()),

    "generated_files": [

        "dataset_inventory.csv",

        "statistical_validation.csv",

        "statistical_summary.json",

        "family1_variation.csv",

        "omega_neutrality.csv",

        "family1_validation.json",

        "family1_certificate.json",

        "family1_certificate.txt",

    ],

}

with open(

    OUTPUT_DIR /
    "campaign_manifest.json",

    "w",

) as f:

    json.dump(

        manifest,

        f,

        indent=4,

    )

# ------------------------------------------------------------
# Execution summary
# ------------------------------------------------------------

summary = []

summary.append("=" * 72)
summary.append("E10.1.4 - FAMILY 1 VALIDATION")
summary.append("=" * 72)
summary.append("")

summary.append("Campaign status")
summary.append("----------------")
summary.append("FINISHED")
summary.append("")

summary.append("Datasets")
summary.append("--------")

for name in datasets.keys():
    summary.append(f"• {name}")

summary.append("")
summary.append("Validation")
summary.append("----------")

summary.append(
    f"Datasets valid .......... {certificate['all_datasets_valid']}"
)

summary.append(
    f"Gamma varies ............ {certificate['gamma_generates_variation']}"
)

summary.append(
    f"Omega neutral ........... {certificate['omega_is_neutral']}"
)

summary.append(
    f"Family approved ......... {certificate['family_validated']}"
)

summary.append("")
summary.append("Decision")
summary.append("--------")
summary.append(decision)

summary.append("")
summary.append("=" * 72)

with open(

    OUTPUT_DIR /
    "execution_summary.txt",

    "w",

) as f:

    f.write("\n".join(summary))

# ------------------------------------------------------------
# Scientific certificate
# ------------------------------------------------------------

campaign_certificate = {

    "campaign": "E10.1.4",

    "validated_family": "Family 1",

    "operator":

        "U(gamma) = (1 + gamma) I",

    "omega":

        "Reserved",

    "criteria": {

        "datasets_valid":

            certificate["all_datasets_valid"],

        "gamma_generates_variation":

            certificate["gamma_generates_variation"],

        "omega_is_neutral":

            certificate["omega_is_neutral"],

        "family_validated":

            certificate["family_validated"],

    },

    "decision":

        decision,

}

with open(

    OUTPUT_DIR /
    "campaign_certificate.json",

    "w",

) as f:

    json.dump(

        campaign_certificate,

        f,

        indent=4,

    )

# ------------------------------------------------------------
# Console
# ------------------------------------------------------------

print()

print("Generated files")

for file in sorted(OUTPUT_DIR.iterdir()):
    print(" -", file.name)

print("\nCampaign successfully completed.")

print("\n" + "=" * 80)
print("E10.1.4 - FAMILY 1 VALIDATION FINISHED")
print("=" * 80)

print(f"\nOutput directory:\n{OUTPUT_DIR}")

# ============================================================
# PART 6
# FINAL AUDIT
# ============================================================

print("\n" + "=" * 80)
print("PART 6 - FINAL AUDIT")
print("=" * 80)

from pathlib import Path
import json

# ------------------------------------------------------------
# Expected files
# ------------------------------------------------------------

expected_files = [

    "dataset_inventory.csv",

    "statistical_validation.csv",

    "statistical_summary.json",

    "family1_variation.csv",

    "omega_neutrality.csv",

    "family1_validation.json",

    "family1_certificate.json",

    "family1_certificate.txt",

    "campaign_manifest.json",

    "execution_summary.txt",

    "campaign_certificate.json",

]

audit = []

missing = []

for filename in expected_files:

    path = OUTPUT_DIR / filename

    exists = path.exists()

    audit.append({

        "file": filename,

        "exists": exists,

        "size_bytes":

            path.stat().st_size
            if exists
            else 0,

    })

    if not exists:

        missing.append(filename)

audit_df = pd.DataFrame(audit)

audit_df.to_csv(

    OUTPUT_DIR /
    "final_audit.csv",

    index=False,

)

# ------------------------------------------------------------
# Campaign completeness
# ------------------------------------------------------------

certificate = {

    "experiment":

        "E10.1.4",

    "files_expected":

        len(expected_files),

    "files_found":

        int(audit_df.exists.sum()),

    "files_missing":

        len(missing),

    "campaign_complete":

        len(missing) == 0,

}

with open(

    OUTPUT_DIR /
    "final_audit.json",

    "w",

) as f:

    json.dump(

        certificate,

        f,

        indent=4,

    )

# ------------------------------------------------------------
# Human-readable report
# ------------------------------------------------------------

report = []

report.append("=" * 72)
report.append("E10.1.4 FINAL AUDIT")
report.append("=" * 72)
report.append("")

for row in audit:

    status = "OK" if row["exists"] else "MISSING"

    report.append(

        f"{status:8} "
        f"{row['file']} "
        f"({row['size_bytes']} bytes)"

    )

report.append("")
report.append("-" * 72)
report.append("")

report.append(

    f"Expected files : {certificate['files_expected']}"

)

report.append(

    f"Files found    : {certificate['files_found']}"

)

report.append(

    f"Files missing  : {certificate['files_missing']}"

)

report.append("")

if certificate["campaign_complete"]:

    report.append("STATUS : COMPLETE")

else:

    report.append("STATUS : INCOMPLETE")

report.append("")
report.append("=" * 72)

with open(

    OUTPUT_DIR /
    "final_audit.txt",

    "w",

) as f:

    f.write("\n".join(report))

# ------------------------------------------------------------
# Console
# ------------------------------------------------------------

print()

print(audit_df)

print("\nCampaign complete :", certificate["campaign_complete"])

print("\nOutput directory")
print(OUTPUT_DIR)

print("\n" + "=" * 80)
print("E10.1.4 AUDIT FINISHED")
print("=" * 80)

# ============================================================
# MAIN
# ============================================================

def main():

    print("\n" + "=" * 80)
    print("GER")
    print("S29 - E10.1.4")
    print("Family 1 Validation")
    print("=" * 80)

    #
    # Parts 1–6 are executed sequentially.
    #

    print("\nExperiment completed successfully.")


if __name__ == "__main__":
    main()
